import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Commomlayout from "@/components/common/layout";
import { SocketProvider } from "@/components/notif/SocketProvider";


export const metadata: Metadata = {
  title: "Isoneday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <SocketProvider>
          
        <Commomlayout>{children}</Commomlayout>
        </SocketProvider>
        <Toaster/>
          
      </body>
    </html>
  );
}
